<?php

namespace App\UssdTraits;

trait Menus{

    public function menu(){
        return '{"menu":[{"id":"root","response":"...",
		   "map":[{"key":"next","menu":"home"}],
		   "type":"static",
		   "action":"con"
		  },{"id":"home",		   
		   "response":"Select Option\n1. My Account\n2. Mobile Money\n3. Payment & Utilities\n4. Funds Transfers\n5. Pesalink \n6. Mobile Loan \n7. Service Requests \n8. Settings \n000. Exit",
		   "map":[{"key":"1","menu":"MyAccount"},{"key":"2","menu":"MobileMoney"},{"key":"3","menu":"Payments"},{"key":"4","menu":"FT"},{"key":"5","menu":"KITS"},{"key":"6","menu":"MobileLoans"},
           {"key":"7","menu":"ServiceRequests"},{"key":"8","menu":"Service"}],
		   "type":"dynamic",
		   "action":"con"
		  },{"id":"MyAccount",		   
		   "response":"Reply with:\n1. Balance enquiry \n2. Mini Statement \n3. Full Statement \n4. Manage Beneficiaries\n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"BalanceAccounts"},{"key":"2","menu":"StatementAccounts"},{"key":"3","menu":"FStatementAccounts"},{"key":"4","menu":"ManageBeneficiary"}],
		   "type":"dynamic",
		   "action":"con"
		  },{"id":"FSatementFrom",
		   "response":"Enter From date (dd/mm/yyyy):",
		   "map":[{"key":"next","menu":"FSatementTo"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"FSatementTo",
		   "response":"Enter To date (dd/mm/yyyy):",
		   "map":[{"key":"next","menu":"AccountFStatement"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"ManageBeneficiary",		   
		   "response":"Reply with:\n1. Add Beneficiary \n2. View Beneficiaries \n3. Delete Beneficiary\n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"AddBeneficiary"},{"key":"2","menu":"ViewBeneficiary"},{"key":"3","menu":"DeleteBeneficiary"}],
		   "type":"dynamic",
		   "action":"con"
		  },{"id":"AddBeneficiary",		   
		   "response":"Reply with:\n1. Sidian Bank Account \n2. Other Banks Account \n3. Pesalink \n4. Airtime \n5. Mpesa \n6. Utilities\n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"Service"},{"key":"2","menu":"BeneficiaryBanksFetcher"},{"key":"3","menu":"BeneficiaryBanksFetcher"},{"key":"4","menu":"AirtimeBeneficiary"},{"key":"5","menu":"MMBAccount"},{"key":"6","menu":"UtilitiesBeneficiary"}],
		   "type":"dynamic",
		   "action":"con"
		  },{"id":"ViewBeneficiary",		   
		   "response":"Reply with:\n1. Sidian Bank Account \n2. Other Banks Account \n3. Pesalink \n4. Airtime \n5. Mpesa \n6. Utilities\n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"GetTransfersBeneficiary"},{"key":"2","menu":"GetTransfersBeneficiary"},{"key":"3","menu":"GetTransfersBeneficiary"},{"key":"4","menu":"ViewAirtimeBeneficiary"},{"key":"5","menu":"GetMobileMoneyBeneficiary"},{"key":"6","menu":"ViewUtilitiesBeneficiary"}],
		   "type":"dynamic",
		   "action":"con"
		  },{"id":"DeleteBeneficiary",		   
		   "response":"Reply with:\n1. Sidian Bank Account \n2. Other Banks Account \n3. Pesalink \n4. Airtime \n5. Mpesa \n6. Utilities\n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"DeleteGetTransfersBeneficiary"},{"key":"2","menu":"DeleteGetTransfersBeneficiary"},{"key":"3","menu":"DeleteGetTransfersBeneficiary"},{"key":"4","menu":"DeleteAirtimeBeneficiary"},{"key":"5","menu":"GetMobileMoneyBeneficiary"},{"key":"6","menu":"DeleteUtilitiesBeneficiary"}],
		   "type":"dynamic",
		   "action":"con"
		  },{"id":"MMBAccount",
		   "response":"Enter Phone Number:",
		   "map":[{"key":"next","menu":"MMBName"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"MMBName",
		   "response":"Enter Beneficiary Name:",
		   "map":[{"key":"next","menu":"AddMobileMoneyBeneficiary"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"ViewAirtimeBeneficiary",		   
		   "response":"Select Biller:\n1. Safaricom \n2. Airtel \n3. Telkom \n4. Airtel Postpaid \n5. Telkom Postpaid\n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"GetAirtimeBeneficiary"},{"key":"2","menu":"GetAirtimeBeneficiary"},{"key":"3","menu":"GetAirtimeBeneficiary"},{"key":"4","menu":"GetAirtimeBeneficiary"},{"key":"5","menu":"GetAirtimeBeneficiary"}],
		   "type":"dynamic",
		   "action":"con"
		  },{"id":"DeleteAirtimeBeneficiary",		   
		   "response":"Select Biller:\n1. Safaricom \n2. Airtel \n3. Telkom \n4. Airtel Postpaid \n5. Telkom Postpaid\n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"DeleteGetAirtimeBeneficiary"},{"key":"2","menu":"DeleteGetAirtimeBeneficiary"},{"key":"3","menu":"DeleteGetAirtimeBeneficiary"},{"key":"4","menu":"DeleteGetAirtimeBeneficiary"},{"key":"5","menu":"DeleteGetAirtimeBeneficiary"}],
		   "type":"dynamic",
		   "action":"con"
		  },{"id":"AirtimeBeneficiary",		   
		   "response":"Select Biller:\n1. Safaricom \n2. Airtel \n3. Telkom \n4. Airtel Postpaid \n5. Telkom Postpaid\n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"ABAccount"},{"key":"2","menu":"ABAccount"},{"key":"3","menu":"ABAccount"},{"key":"4","menu":"ABAccount"},{"key":"5","menu":"ABAccount"}],
		   "type":"dynamic",
		   "action":"con"
		  },{"id":"ABAccount",
		   "response":"Enter Phone Number:",
		   "map":[{"key":"next","menu":"ABName"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"ABName",
		   "response":"Enter Beneficiary Name:",
		   "map":[{"key":"next","menu":"AddAirtimeBeneficiary"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"ViewUtilitiesBeneficiary",		   
		   "response":"Select Biller:\n1. KPLC \n2. Nairobi Water \n3. DSTV \n4. GOTV \n5. STARTIMES \n6. ZUKU \n7 JTL \n8 Access Kenya.\n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"GetUtilitiesBeneficiary"},{"key":"2","menu":"GetUtilitiesBeneficiary"},{"key":"3","menu":"GetUtilitiesBeneficiary"},{"key":"4","menu":"GetUtilitiesBeneficiary"},
		   {"key":"5","menu":"GetUtilitiesBeneficiary"},{"key":"6","menu":"GetUtilitiesBeneficiary"},{"key":"7","menu":"GetUtilitiesBeneficiary"},{"key":"8","menu":"GetUtilitiesBeneficiary"}],
		   "type":"dynamic",
		   "action":"con"
		  },{"id":"DeleteUtilitiesBeneficiary",		   
		   "response":"Select Biller:\n1. KPLC \n2. Nairobi Water \n3. DSTV \n4. GOTV \n5. STARTIMES \n6. ZUKU \n7 JTL \n8 Access Kenya.\n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"DeleteGetUtilitiesBeneficiary"},{"key":"2","menu":"DeleteGetUtilitiesBeneficiary"},{"key":"3","menu":"DeleteGetUtilitiesBeneficiary"},{"key":"4","menu":"DeleteGetUtilitiesBeneficiary"},
		   {"key":"5","menu":"DeleteGetUtilitiesBeneficiary"},{"key":"6","menu":"DeleteGetUtilitiesBeneficiary"},{"key":"7","menu":"DeleteGetUtilitiesBeneficiary"},{"key":"8","menu":"DeleteGetUtilitiesBeneficiary"}],
		   "type":"dynamic",
		   "action":"con"
		  },{"id":"UtilitiesBeneficiary",		   
		   "response":"Select Biller:\n1. KPLC \n2. Nairobi Water \n3. DSTV \n4. GOTV \n5. STARTIMES \n6. ZUKU \n7 JTL \n8 Access Kenya.\n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"UBAccount"},{"key":"2","menu":"UBAccount"},{"key":"3","menu":"UBAccount"},{"key":"4","menu":"UBAccount"},{"key":"5","menu":"UBAccount"},{"key":"6","menu":"UBAccount"},{"key":"7","menu":"UBAccount"},{"key":"8","menu":"UBAccount"}],
		   "type":"dynamic",
		   "action":"con"
		  },{"id":"UBAccount",
		   "response":"Enter Account Number:",
		   "map":[{"key":"next","menu":"UBName"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"UBName",
		   "response":"Enter Beneficiary Name:",
		   "map":[{"key":"next","menu":"AddUtilitiesBeneficiary"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"BeneficiaryBank",
		   "response":"Enter Recipient Bank:",
		   "map":[{"key":"next","menu":"BeneficiaryBankAccount"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"BeneficiaryBankAccount",
		   "response":"Enter Recipient Account:",
		   "map":[{"key":"next","menu":"BeneficiaryBankName"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"BeneficiaryBankName",
		   "response":"Enter Beneficiary Name:",
		   "map":[{"key":"next","menu":"AddTransfersBeneficiary"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"MobileMoney",
		   "response":"1. Account to M-PESA \n2. Airtime Top-Up \n3. Buy Float \n4. Buy Goods \n5. Paybill \n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"AccToMpesa"},{"key":"2","menu":"AirtimeTopup"},{"key":"3","menu":"MMBillsAccounts"},{"key":"4","menu":"MMBillsAccounts"},{"key":"5","menu":"MMBillsAccounts"}],
		   "type":"dynamic",		   
		   "action":"con"
		  },{"id":"BuyFloatAgent",
		   "response":"Enter Agent Number:",
		   "map":[{"key":"next","menu":"BuyFloatAmount"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"BuyFloatAmount",
		   "response":"Enter Amount:",
		   "map":[{"key":"next","menu":"BuyFloatRemarks"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"BuyFloatRemarks",
		   "response":"Enter Remakrs:",
		   "map":[{"key":"next","menu":"BuyFloatConfirm"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"BuyGoodsTill",
		   "response":"Enter Till Number:",
		   "map":[{"key":"next","menu":"BuyGoodsAmount"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"BuyGoodsAmount",
		   "response":"Enter Amount:",
		   "map":[{"key":"next","menu":"BuyGoodsRemarks"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"BuyGoodsRemarks",
		   "response":"Enter Remarks:",
		   "map":[{"key":"next","menu":"BuyGoodsConfirm"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"PayBillNumber",
		   "response":"Enter PayBill Number:",
		   "map":[{"key":"next","menu":"PayBillAccount"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"PayBillAccount",
		   "response":"Enter Account Number:",
		   "map":[{"key":"next","menu":"PayBillAmount"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"PayBillAmount",
		   "response":"Enter Amount:",
		   "map":[{"key":"next","menu":"PayBillRemarks"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"PayBillRemarks",
		   "response":"Enter Remarks:",
		   "map":[{"key":"next","menu":"PayBillConfirm"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"AccToMpesa",
		   "response":"1. Own number \n2. Other number \n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"MobileMoneyAccounts"},{"key":"2","menu":"MobileMoneyOtherAccounts"}],
		   "type":"dynamic",		   
		   "action":"con"
		  },{"id":"AccToMpesaRecipient",
		   "response":"1. Enter Recipient \n2. Select Beneficiary \n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"formMsisdnMM"},{"key":"2","menu":"Service"}],
		   "type":"dynamic",		   
		   "action":"con"
		  },{"id":"AirtimeTopup",
		   "response":"1. Own number \n2. Other number \n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"AirtimeOwnAccounts"},{"key":"2","menu":"AirtimeOtherAccounts"}],
		   "type":"dynamic",		   
		   "action":"con"
		  },{"id":"AirtimeRecipient",
		   "response":"1. Enter Recipient \n2. Select Beneficiary \n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"pinlessMsisdn2"},{"key":"2","menu":"Service"}],
		   "type":"dynamic",		   
		   "action":"con"
		  },{"id":"Payments",
		   "response":"1. Utilities \n2. School fees payments \n3. Insurance premiums \n0. Home \n.000. Exit",
		   "map":[{"key":"1","menu":"utilitypayment"},{"key":"2","menu":"Service"},{"key":"3","menu":"Service"},{"key":"4","menu":"Service"},{"key":"5","menu":"Service"}],
		   "type":"dynamic",
           "name":"un",
		   "link":"",
		   "action":"con"
		  },{"id":"FT",
		   "response":"1. Account to Account \n2. Account to other bank \n3.RTGS \n4. Send to Card\n0. Home \n.000. Exit",
		   "map":[{"key":"1","menu":"IFTAccounts"},{"key":"2","menu":"EFTAccounts"},{"key":"3","menu":"RTGSAccounts"},{"key":"4","menu":"SendToCard"}],
		   "type":"dynamic",
           "name":"FT",
		   "link":"",
		   "action":"con"
		  },{"id":"RTGSBanksFilter",
		   "response":"Select Bank Category:\n1. A-B\n2. C\n3. D-E\n4. F\n5.G-H\n6. I-M\n7. N-S\n8 T-Z\n00. Home",
		   "map":[{"key":"next","menu":"RecipientBanksFetcherRTGS"}],
		   "type":"form",
           "name":"kitsbanksearch",
		   "action":"cont"
		  },{"id":"RTGSBranchFilter",
		   "response":"Select Bank Category:\n1. A-B\n2. C\n3. D-E\n4. F\n5.G-H\n6. I-M\n7. N-S\n8 T-Z\n00. Home",
		   "map":[{"key":"next","menu":"RecipientBranchFetcherRTGS"}],
		   "type":"form",
           "name":"kitsbanksearch",
		   "action":"cont"
		  },{"id":"rtgsFormRecipientAccount",
		   "response":"Enter Recipient Account Number:",
		   "map":[{"key":"next","menu":"rtgsFormRecipientName"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"rtgsFormRecipientName",
		   "response":"Enter Recipient Name:",
		   "map":[{"key":"next","menu":"rtgsFormAmount"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"rtgsFormAmount",
		   "response":"Enter Amount to Send:",
		   "map":[{"key":"next","menu":"rtgsFormNarration"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"rtgsFormNarration",
		   "response":"Enter Remarks:",
		   "map":[{"key":"next","menu":"rtgsConfirm"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"SendToCard",
		   "response":"1. Pre-paid Card \n2. Credit Card \n0. Home \n.000. Exit",
		   "map":[{"key":"1","menu":"SendToCardAccounts"},{"key":"2","menu":"SendToCardAccounts"}],
		   "type":"dynamic",
           "name":"FT",
		   "link":"",
		   "action":"con"
		  },{"id":"STCCardNumber",
		   "response":"Enter Card Number:",
		   "map":[{"key":"next","menu":"STCAmount"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"STCAmount",
		   "response":"Enter Amount to Send:",
		   "map":[{"key":"next","menu":"STCNarration"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"STCNarration",
		   "response":"Enter Remarks:",
		   "map":[{"key":"next","menu":"SendToCardConfirm"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"IFT",
		   "response":"Select \n1. Own Account \n2. Other Account \n0. Home \n.000. Exit",
		   "map":[{"key":"1","menu":"iftFormRecipientAccount"},{"key":"2","menu":"iftFormRecipientAccount"}],
		   "type":"dynamic",
           "name":"IFT",
		   "link":"",
		   "action":"con"
		  },{"id":"iftFormRecipientAccount",
		   "response":"Enter Recipient Account Number:",
		   "map":[{"key":"next","menu":"iftFormAmount"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"iftFormAmount",
		   "response":"Enter Amount to Send:",
		   "map":[{"key":"next","menu":"iftFormNarration"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"iftFormNarration",
		   "response":"Enter Remarks:",
		   "map":[{"key":"next","menu":"iftConfirm"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"EFT",
		   "response":"Select \n1. Enter Recipient Account \n2. Select Beneficiary \n0. Home \n.000. Exit",
		   "map":[{"key":"1","menu":"eftFormRecipientAccount"},{"key":"2","menu":"Service"}],
		   "type":"dynamic",
           "name":"EFT",
		   "link":"",
		   "action":"con"
		  },{"id":"eftFormRecipientAccount",
		   "response":"Enter Recipient Account Number:",
		   "map":[{"key":"next","menu":"eftFormRecipientName"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"eftFormRecipientName",
		   "response":"Enter Recipient Name:",
		   "map":[{"key":"next","menu":"eftsFormAmount"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"eftsFormAmount",
		   "response":"Enter Amount to Send:",
		   "map":[{"key":"next","menu":"eftFormNarration"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"eftFormNarration",
		   "response":"Enter Remarks:",
		   "map":[{"key":"next","menu":"eftsConfirm"}],
		   "type":"form",
		   "action":"con"
		  },{"id":"KITS",
		   "response":"1. Registration \n2. Nominate primary account \n3. Send to Card \n4. Send to Account \n5. Send to Phone \n0. Home \n.000. Exit",
		   "map":[{"key":"1","menu":"KITSAccounts"},{"key":"2","menu":"KITSAccounts"},{"key":"3","menu":"KITSAccounts"},{"key":"4","menu":"KITSAccounts"},{"key":"5","menu":"KITSAccounts"}],
		   "type":"dynamic",
           "name":"KITS",
		   "link":"",
		   "action":"con"
		  },{"id":"payaccount",
		   "response":"Enter Recipient Account:",
		   "map":[{"key":"next","menu":"trxbank"}],
		   "type":"form",
           "name":"kitsRacc",
		   "action":"cont"
		  },{"id":"trxbank",
		   "response":"Select Bank Category:\n1. A-B\n2. C\n3. D-E\n4. F\n5.G-H\n6. I-M\n7. N-S\n8 T-Z\n00. Home",
		   "map":[{"key":"next","menu":"beneficiarybank"}],
		   "type":"form",
           "name":"kitsbanksearch",
		   "action":"cont"
		  },{"id":"trxaccamount",
		   "response":"Enter send amount:",
		   "map":[{"key":"next","menu":"trxRaccnarration"}],
		   "type":"form",
           "name":"kitsaccamount",
		   "action":"cont"
		  },{"id":"trxRaccnarration",
		   "response":"Enter transaction narration:",
		   "map":[{"key":"next","menu":"AccKitsConfirm"}],
		   "type":"form",
           "name":"kitsaccnarration",
		   "action":"cont"
		  },{"id":"payphone",
		   "response":"Enter Phone Number:",
		   "map":[{"key":"next","menu":"validatekitsdetails_New"}],
		   "type":"form",
           "name":"kitsRphone",
		   "action":"cont"
		  },{"id":"trxamount",
		   "response":"Enter send amount:",
		   "map":[{"key":"next","menu":"trxnarration"}],
		   "type":"form",
           "name":"kitsppamount",
		   "action":"cont"
		  },{"id":"trxnarration",
		   "response":"Enter transaction narration:",
		   "map":[{"key":"next","menu":"P2PKitsConfirm"}],
		   "type":"form",
           "name":"kitsppnarration",
		   "action":"cont"
		  },{"id":"paycard",
		   "response":"Enter Recipient Card Number:",
		   "map":[{"key":"next","menu":"cardamt"}],
		   "type":"form",
           "name":"kitsRcard",
		   "action":"cont"
		  },{"id":"cardamt",
		   "response":"Enter Send Amount:",
		   "map":[{"key":"next","menu":"trxRcardnarration"}],
		   "type":"form",
           "name":"kitsRcardamount",
		   "action":"cont"
		  },{"id":"trxRcardnarration",
		   "response":"Enter Reason For Paymnet:",
		   "map":[{"key":"next","menu":"CardKitsConfirm"}],
		   "type":"form",
           "name":"kitscardnarration",
		   "action":"cont"
		  },{"id":"MobileLoans",
		   "response":"1. Request Loan \n2. Pay Loan \n3. Loan Terms \n4. Credit Status \n0. Home \n.000. Exit",
		   "map":[{"key":"1","menu":"utilitypayment"},{"key":"2","menu":"ticketsasa"}],
		   "type":"dynamic",
           "name":"MobileLoans",
		   "link":"",
		   "action":"con"
		  },{"id":"utilitypayment",
		   "response":"Utility Payment \n1. KPLC Prepaid \n2. KPLC Postpaid \n3. Nairobi Water \n4. Pay TV Package \n5. Pay Internet \n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"UtilityAccounts"},{"key":"2","menu":"UtilityAccounts"},{"key":"3","menu":"UtilityAccounts"},
                   {"key":"4","menu":"PayTV"},{"key":"5","menu":"PayInternet"}],
		   "type":"dynamic",
           "name":"un",
		   "link":"",
		   "action":"con"
		  },{"id":"PayTV",
		   "response":"Select TV Package \n1. DSTV \n2. GOTV \n3. STARTIMES \n4. ZUKU \n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"UtilityAccounts"},{"key":"2","menu":"UtilityAccounts"},{"key":"3","menu":"UtilityAccounts"},
                   {"key":"4","menu":"UtilityAccounts"}],
		   "type":"dynamic",
           "name":"un",
		   "link":"",
		   "action":"con"
		  },{"id":"PayInternet",
		   "response":"Select Internet Service \n1. JTL \n2. Access Kenya \n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"UtilityAccounts"},{"key":"2","menu":"UtilityAccounts"}],
		   "type":"dynamic",
           "name":"un",
		   "link":"",
		   "action":"con"
		  },{"id":"formMerchantAmount",
		   "response":"Enter amount:",
		   "map":[{"key":"next","menu":"UtilityConfirm"}],
		   "type":"form",
		   "name":"fAmount",
		   "action":"cont"
		  },{"id":"formMerchantAccount",
		   "response":"Enter your Account number:",
		   "map":[{"key":"next","menu":"formMerchantAmount"}],
		   "type":"form",
		   "name":"ac",
		   "action":"cont"
		  },{"id":"Agency",
		   "response":"1. Widthdraw from Agent \n2. Widthdraw from ATM \n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"AccToMpesa"},{"key":"2","menu":"AirtelformNumber"}],
		   "type":"dynamic",		   
		   "action":"con"
		  },{"id":"ServiceRequests",
		   "response":"1.Cheque book \n2. Standing orders \n3. Term Deposits \n4. Manage Cards \n5. Account Opening \n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"ChequeBook"},{"key":"2","menu":"StandingOrders"},{"key":"3","menu":"TermDeposit"},{"key":"4","menu":"ManageCards"},{"key":"5","menu":"BankProducts"}],
		   "type":"dynamic",		   
		   "action":"con"
		  },{"id":"NewAccountName",
		   "response":"Enter Account Name:",
		   "map":[{"key":"next","menu":"NewAccountCreate"}],
		   "type":"form",
		   "name":"ac",
		   "action":"cont"
		  },{"id":"ChequeBook",
		   "response":"1.Cheque book order\n2. Stop cheque\n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"ChequeBookAccounts"},{"key":"2","menu":"ChequeBookAccounts"}],
		   "type":"dynamic",		   
		   "action":"con"
		  },{"id":"ChequeBookOrder",
		   "response":"Select number of leaves \n1. 25 \n2. 50 \n3. 100\n000. Exit",
		   "map":[{"key":"1","menu":"ChequeBookOrderConfirm"},{"key":"2","menu":"ChequeBookOrderConfirm"},{"key":"2","menu":"ChequeBookOrderConfirm"}],
		   "type":"dynamic",		   
		   "action":"con"
		  },{"id":"FromChequeNo",
		   "response":"From cheque number:\n000. Exit",
		   "map":[{"key":"next","menu":"ToChequeNo"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"ToChequeNo",
		   "response":"To cheque number: \n000. Exit",
		   "map":[{"key":"1","menu":"ChequeBookStopConfirm"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"TermDeposit",
		   "response":"1. Fixed Deposit order\n2. Call Deposit\n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"TermDepositAccounts"},{"key":"2","menu":"TermDepositAccounts"}],
		   "type":"dynamic",		   
		   "action":"con"
		  },{"id":"TDTenure",
		   "response":"Select Tenure: \n1. Month \n2. 3 Months \n3. 6 Months \n4. 9 Months \n5. 1 Year \n000. Exit",
		   "map":[{"key":"1","menu":"TDAmount"},{"key":"2","menu":"TDAmount"},{"key":"3","menu":"TDAmount"},{"key":"4","menu":"TDAmount"},{"key":"5","menu":"TDAmount"}],
		   "type":"dynamic",		   
		   "action":"con"
		  },{"id":"TDAmount",
		   "response":"Enter Amount: \n000. Exit",
		   "map":[{"key":"next","menu":"TermDepositConfirm"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"StandingOrders",
		   "response":"1.Setup standing orders\n2. My standing orders\n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"StandingOrderType"},{"key":"2","menu":"StandingOrderAccounts"}],
		   "type":"dynamic",		   
		   "action":"con"
		  },{"id":"StandingOrderType",
		   "response":"1.Internal Standing Order\n2. External Standing Order\n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"StandingOrderAccounts"},{"key":"2","menu":"ExternalStandingOrderAccounts"}],
		   "type":"dynamic",		   
		   "action":"con"
		  },{"id":"SOAccount",
		   "response":"Enter recipient Account number:\n000. Exit",
		   "map":[{"key":"next","menu":"SOName"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"SOName",
		   "response":"Enter recipient name:\n000. Exit",
		   "map":[{"key":"next","menu":"SOAmount"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"SOAmount",
		   "response":"Enter Amount:\n000. Exit",
		   "map":[{"key":"next","menu":"SOStartDate"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"SOStartDate",
		   "response":"Enter start date (dd/mm/yyyy):\n000. Exit",
		   "map":[{"key":"next","menu":"SOFrequency"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"SOFrequency",
		   "response":"Enter frequency:\n000. Exit",
		   "map":[{"key":"next","menu":"SOExecutions"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"SOExecutions",
		   "response":"Enter number of executions:\n000. Exit",
		   "map":[{"key":"next","menu":"SOLastDate"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"SOLastDate",
		   "response":"Enter last execution date (dd/mm/yyyy):\n000. Exit",
		   "map":[{"key":"next","menu":"StandingOrderConfirm"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"ESOBanksFilter",
		   "response":"Select Bank Category:\n1. A-B\n2. C\n3. D-E\n4. F\n5.G-H\n6. I-M\n7. N-S\n8 T-Z\n00. Home",
		   "map":[{"key":"next","menu":"RecipientBanksFetcherESO"}],
		   "type":"form",
           "name":"kitsbanksearch",
		   "action":"cont"
		  },{"id":"ESOBranchFilter",
		   "response":"Select Bank Category:\n1. A-B\n2. C\n3. D-E\n4. F\n5.G-H\n6. I-M\n7. N-S\n8 T-Z\n00. Home",
		   "map":[{"key":"next","menu":"RecipientBranchFetcherESO"}],
		   "type":"form",
           "name":"kitsbanksearch",
		   "action":"cont"
		  },{"id":"ESOAccount",
		   "response":"Enter recipient Account number:\n000. Exit",
		   "map":[{"key":"next","menu":"ESOName"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"ESOName",
		   "response":"Enter recipient name:\n000. Exit",
		   "map":[{"key":"next","menu":"ESOAmount"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"ESOAmount",
		   "response":"Enter Amount:\n000. Exit",
		   "map":[{"key":"next","menu":"ESOStartDate"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"ESOStartDate",
		   "response":"Enter start date (dd/mm/yyyy):\n000. Exit",
		   "map":[{"key":"next","menu":"ESOFrequency"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"ESOFrequency",
		   "response":"Enter frequency:\n000. Exit",
		   "map":[{"key":"next","menu":"ESOExecutions"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"ESOExecutions",
		   "response":"Enter number of executions:\n000. Exit",
		   "map":[{"key":"next","menu":"ESOLastDate"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"ESOLastDate",
		   "response":"Enter last execution date (dd/mm/yyyy):\n000. Exit",
		   "map":[{"key":"next","menu":"ExternalStandingOrderConfirm"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"ManageCards",
		   "response":"1.Debit card order\n2.Block debit card \n3. Apply credit card \n4. Block credit card\n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"CardAccounts"},{"key":"2","menu":"CardAccounts"},{"key":"3","menu":"CardAccounts"},{"key":"4","menu":"CardAccounts"}],
		   "type":"dynamic",		   
		   "action":"con"
		  },{"id":"AccToMpesa",
		   "response":"Reply with: \n1. To Own Mobile \n2. To Other Mobile \n0. Home \n000. Exit",
		   "map":[{"key":"1","menu":"formNumber"},{"key":"2","menu":"AirtelformNumber"}],
		   "type":"dynamic",		   
		   "action":"con"
		  },{"id":"formNumber",
		   "response":"1. To My Phone\n2. To Other Phone\n0. Home\n000.Exit",
		   "map":[{"key":"1","menu":"formAmountMM"},
                  {"key":"2","menu":"formMsisdnMM"}],
		   "type":"dynamic",		   
		   "action":"con"
		  },{"id":"formAmountMM",
		   "response":"Enter amount to send:\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"MobileMoneyConfirm"}],
		   "type":"form",
           "name":"fAmount",
		   "link":"",
		   "action":"con"
          },{"id":"formMsisdnMM",
		   "response":"Enter Number to send Mpesa to:\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"formAmountMM"}],
		   "type":"form",
           "name":"fMsisdn",
		   "link":"",
		   "action":"con"
          },{"id":"AirtelformNumber",
		   "response":"1. To My Phone\n2. To Other Phone\n0. Home\n000.Exit",
		   "map":[{"key":"1","menu":"formAmountAirtelMoney"},
                  {"key":"2","menu":"formAirtelMoney"}],
		   "type":"dynamic",		   
		   "action":"con"
		  },{"id":"formAirtelMoney",
		   "response":"Enter Number to send Airtel Money to:\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"formAmountAirtelMoney"}],
		   "type":"form",
           "name":"fMsisdn",
		   "link":"",
		   "action":"con"
          },{"id":"formAmountAirtelMoney",
		   "response":"Enter amount to send:\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"account"},{"key":"postMenu","menu":"airtelConfirm"}],
		   "type":"form",
           "name":"fAmount",
		   "link":"",
		   "action":"con"
          },{"id":"iftFormAccount",
		   "response":"Enter Account To Transfer To:\n0. Home\n000.Exit",
           "map":[{"key":"next","menu":"VerifyAccount"}],
		   "type":"form",
           "name":"DirectAccount",		   
		   "action":"con"
		  },{"id":"iftFormAmountDirect",
		   "response":"Enter Amount To Transfer:\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"accountIFTDirectConfirm"}],
		   "type":"form",
           "name":"DirectAmount",		   
		   "action":"con"
		  },{"id":"iftFormAmount",
		   "response":"Enter Amount To Transfer:\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"accountIFTConfirm"},{"key":"header","menu":"account"}],
		   "type":"form",		   
		   "action":"con"
		  },{"id":"formAccount", 
		   "response":"Enter your Account number:\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"navigateutilitymenu"}],
		   "type":"form",
		   "name":"ac",
		   "action":"con"
		  },{"id":"dstvaccoption",
		   "response":"Select Account Option\n1. CUSTOMERNUMBER\n2. SMARTCARD\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"dstvinvperiod"},
                {"key":"1","menu":"CUSTOMERNUMBER"},{"key":"2","menu":"SMARTCARD"}],
		   "type":"dynamic",
           "name":"dsacc",
		   "link":"",
		   "action":"con"
		  },{"id":"dstvinvperiod",
		   "response":"Select Invoice Period\n1. Monthly \n2. Yearly\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"dstvValidate"},
                {"key":"1","menu":"Monthly"},{"key":"2","menu":"Yearly"}],
		   "type":"dynamic",
           "name":"dsperiod",
		   "link":"",
		   "action":"con"
		  },{"id":"formAmount",
		   "response":"Enter amount:\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"account"}],
		   "type":"form",
           "name":"fAmount",
		   "link":"",
		   "action":"con"
          },{"id":"MOBILEPROVIDER",
		   "response":"1. My Phone\n2. Other Phone\n0. Home\n000.Exit",
		   "map":[{"key":"1","menu":"PinlessAirtimeAmount"},{"key":"2","menu":"Network"}],
		   "type":"dynamic",		   
		   "action":"con"
		  },{"id":"Network",
		   "response":"Select Provider\n1. Airtel\n2. Orange\n3. Safaricom\n0. Home\n000.Exit",
		   "map":[{"key":"1","menu":"pinlessMsisdn2"},{"key":"2","menu":"pinlessMsisdn2"},
                  {"key":"3","menu":"pinlessMsisdn2"},{"key":"4","menu":"pinlessMsisdn2"}],
		   "type":"dynamic",
           "name":"networkname",		   
		   "action":"con"
		  },{"id":"pinlessMsisdn2",
		   "response":"Enter mobile number:\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"PinlessAirtimeAmount"}],
		   "type":"form",
           "name":"fAmount",
		   "link":"",
		   "action":"con"
          },{"id":"PinlessAirtimeAmount",
		   "response":"Enter Airtime Amount:\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"Airtime"}],
		   "type":"form",
           "name":"pAmount",
		   "link":"",
		   "action":"con"
          },{"id":"kits",
		   "response":"Reply with:\n1. Pay to Phone\n2. Pay to Account\n3. Pay to Card\n4. Link your Phone\n5. Set Primary Account\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"accountKITS"},{"key":"1","menu":"payphone"},{"key":"2","menu":"payaccount"},{"key":"3","menu":"paycard"},{"key":"4","menu":"LinkPhoneConfirm"},{"key":"5","menu":"SetPrimaryAccountConfirm"}],
		   "type":"dynamic",
           "name":"kitsmenu",
		   "link":"",
		   "action":"con"
		  },{"id":"payphone",
		   "response":"Enter Phone Number:\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"validatekitsdetails"}],
		   "type":"form",
           "name":"kitsRphone",		   
		   "action":"con"
		  },{"id":"trxamount",
		   "response":"Enter send amount:\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"trxnarration"}],
		   "type":"form",
           "name":"kitsppamount",		   
		   "action":"con"
		  },{"id":"trxnarration",
		   "response":"Enter transaction narration:\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"P2PKitsConfirm"}],
		   "type":"form",
           "name":"kitsppnarration",		   
		   "action":"con"
		  },{"id":"payaccount",
		   "response":"Enter Recipient Account:\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"trxbank"}],
		   "type":"form",
           "name":"kitsRacc",		   
		   "action":"con"
		  },{"id":"trxbank",
		   "response":"Select Bank Category:\n1. A-B\n2. C\n3. D-E\n4. F\n5.G-H\n6. I-M\n7. N-S\n8 T-Z\n00. Home",
		   "map":[{"key":"next","menu":"beneficiarybank"}],
		   "type":"form",
           "name":"kitsbanksearch",		   
		   "action":"con"
		  },{"id":"talkToUs",		   
		   "response":"1. Call us on 0711058000 \n2. E-mail us on talktous@sidianbank.co.ke \n3. Chat us on FaceBook - @SidianBank \n4. Chat us on Twitter -@sidianbank \n5. Chat us on Instagram- @sidianbank \n000. Exit",
		   "map":[{"key":"1","menu":"MyAccount"},{"key":"2","menu":"MobileMoney"},{"key":"3","menu":"Payments"},{"key":"4","menu":"FT"},{"key":"5","menu":"KITS"},{"key":"6","menu":"MobileLoans"},
           {"key":"7","menu":"Agency"},{"key":"8","menu":"ServiceRequests"},{"key":"9","menu":"Mvisa"}],
		   "type":"dynamic",
		   "action":"con"
		  },{"id":"trxaccamount",
		   "response":"Enter send amount:\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"trxRaccnarration"}],
		   "type":"form",
           "name":"kitsaccamount",		   
		   "action":"con"
		  },{"id":"trxRaccnarration",
		   "response":"Enter transaction narration:\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"AccKitsConfirm"}],
		   "type":"form",
           "name":"kitsaccnarration",		   
		   "action":"con"
		  },{"id":"paycard",
		   "response":"Enter Recipient Card Number:\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"cardamt"}],
		   "type":"form",
           "name":"kitsRcard",		   
		   "action":"con"
		  },{"id":"cardamt",
		   "response":"Enter Send Amount:\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"trxRcardnarration"}],
		   "type":"form",
           "name":"kitsRcardamount",		   
		   "action":"con"
		  },{"id":"trxRcardnarration",
		   "response":"Enter Reason For Payment:\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"CardKitsConfirm"}],
		   "type":"form",
           "name":"kitscardnarration",		   
		   "action":"con"
		  },{"id":"changePin",
		   "response":"Enter your old pin:\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"newPin1"}],
		   "type":"form",
           "name":"oldPin",		   
		   "action":"con"
		  },{"id":"newPin1",
		   "response":"Enter a new pin:\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"newPin2"}],
		   "type":"form",
           "name":"newPin1",		   
		   "action":"con"
		  },{"id":"newPin2",
		   "response":"Renter your new pin:\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"pinChangeConfirmNew"}],
		   "type":"form",
           "name":"newPin2",		   
		   "action":"con"
		  },{"id":"ComingSoon",
		   "response":"Service is temporarily un-available. Please try again later.",
		   "map":[{"key":"next","menu":"home"}],
		   "type":"static",		   
		   "action":"end"
		  },{"id":"end",
		   "response":"Request successfully submitted. You will receive a confirmation SMS shortly.",
		   "map":[{"key":"next","menu":"root"}],
		   "type":"static",
		   "link":"",
		   "action":"end"
		  },{"id":"cancel",
		   "response":"Transaction canceled, Reply with \n0 for home menu\n0. Home\n000.Exit",
		   "map":[{"key":"next","menu":"home"}],
		   "type":"static",
		   "link":"",
		   "action":"con"
		  },{"id":"subregister",
		   "response":"Please contact the bank to register for this service.",
		   "map":[{"key":"next","menu":"root"}],
		   "type":"static",
		   "link":"",
		   "action":"end"
		  },{"id":"register",
		   "response":"Please contact the bank to register for this service.",
		   "map":[{"key":"next","menu":"root"}],
		   "type":"static",
		   "link":"",
		   "action":"end"
		  },{"id":"Service",
		   "response":"Feature currently not available",
		   "map":[{"key":"next","menu":"root"}],
		   "type":"static",
		   "link":"",
		   "action":"end"
		  }
]}';
    }

}
